'use client';
import { useEffect, useState } from 'react';
import type { Transaction, TraceEvent } from '../lib/store';
import { defaultPolicy, type Policy, type runEvaluations } from '../lib/engine';
type Scenario = {
    id: string;
    name: string;
    description: string;
    category: string;
    amount: number;
};
type Data = {
    transactions: Transaction[];
    policy: Policy;
    evaluation: ReturnType<typeof runEvaluations> | null;
    scenarios: Scenario[];
    workspace: string;
};
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
const names: Record<string, string> = { paid: 'Paid', authorized: 'Authorized', review: 'Needs review', blocked: 'Blocked', rejected: 'Rejected' };
const nav = [['◫', 'Overview'], ['⇄', 'Transactions'], ['⑂', 'MoneyTrace'], ['◇', 'Approvals'], ['⊞', 'Security evals'], ['⚙', 'Policies'], ['⌘', 'Integrations']];
export default function Home() {
    const [data, setData] = useState<Data | null>(null), [page, setPage] = useState('Overview'), [error, setError] = useState(''), [busy, setBusy] = useState(''), [selected, setSelected] = useState(''), [scenario, setScenario] = useState('all'), [filter, setFilter] = useState('all'), [search, setSearch] = useState(''), [node, setNode] = useState<TraceEvent | null>(null), [note, setNote] = useState(''), [draft, setDraft] = useState<Policy>(defaultPolicy), [replay, setReplay] = useState(0), [notice, setNotice] = useState('');
    useEffect(() => { fetch('/api/vault').then(async (r) => { const d = await r.json() as Data & {
        error?: string;
    }; if (!r.ok)
        throw new Error(d.error); setData(d); setDraft(d.policy); setSelected(d.transactions[0]?.id ?? ''); }).catch(e => setError(e.message)); }, []);
    const txs = data?.transactions ?? [], tx = txs.find(t => t.id === selected) ?? txs[0], pending = txs.filter(t => t.status === 'review');
    useEffect(() => { if (!replay)
        return; const timer = setTimeout(() => setReplay(n => n >= ((tx?.trace.length ?? 0) + 1) ? 0 : n + 1), 650); return () => clearTimeout(timer); }, [replay, tx?.trace.length]);
    async function act(action: string, body: Record<string, unknown> = {}) { if (busy)
        return; setBusy(action); setError(''); setNotice(''); try {
        const r = await fetch('/api/vault', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...body }) });
        const d = await r.json() as Data & {
            error?: string;
        };
        if (!r.ok)
            throw new Error(d.error ?? 'Request failed');
        setData(d);
        setDraft(d.policy);
        if (action === 'run') {
            const attacked = d.transactions.find((t: Transaction) => t.run_id === body.runId && t.scenario === 'impersonation');
            setSelected(attacked?.id ?? d.transactions[0]?.id);
            setReplay(1);
            setPage('Overview');
        }
        if (action === 'policy')
            setNotice('Policy saved. New authorizations use these limits.');
        if (action === 'review')
            setNote('');
        return d;
    }
    catch (e) {
        setError(e instanceof Error ? e.message : 'Request failed');
    }
    finally {
        setBusy('');
    } }
    function pick(t: Transaction, target = 'MoneyTrace') { setSelected(t.id); setPage(target); setNode(null); setReplay(0); setNote(''); }
    function exportTrace() { if (!tx)
        return; const url = URL.createObjectURL(new Blob([JSON.stringify(tx, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `agentvault-${tx.invoice}.json`; a.click(); URL.revokeObjectURL(url); }
    const paid = txs.filter(t => t.status === 'paid').reduce((n, t) => n + t.amount / 100, 0), protectedTotal = txs.filter(t => t.status === 'blocked').reduce((n, t) => n + t.amount / 100, 0);
    const visible = txs.filter(t => (filter === 'all' || t.status === filter) && `${t.evidence.vendor} ${t.invoice}`.toLowerCase().includes(search.toLowerCase()));
    function table(items: Transaction[]) { return <div className="table-scroll"><table><thead><tr><th>VENDOR / INVOICE</th><th>AMOUNT</th><th>RISK SCORE</th><th>DECISION</th><th>PROVENANCE</th></tr></thead><tbody>{items.map(t => <tr key={t.id} className={t.id === tx?.id ? 'selected-row' : ''}><td><button className="vendor-button" onClick={() => pick(t)}><span className={`vendor-icon ${t.status}`}>{t.evidence.vendor.split(' ').map(s => s[0]).slice(0, 2).join('')}</span><span><b>{t.evidence.vendor}</b><small>{t.invoice} · {new Date(t.created).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></span></button></td><td className="amount">{money(t.amount / 100)}<small>USD</small></td><td><span className={`risk-num ${t.assessment.fraud >= 80 ? 'red' : t.assessment.fraud >= 45 ? 'amber' : 'green'}`}>{t.assessment.fraud}<small>/100</small></span><div className="mini-bar"><i style={{ width: `${t.assessment.fraud}%`, background: t.assessment.fraud >= 80 ? '#c75551' : t.assessment.fraud >= 45 ? '#bd923e' : '#4a9779' }}/></div></td><td><span className={`status ${t.status}`}>● &nbsp;{names[t.status]}</span></td><td><button className="text-button" onClick={() => pick(t)}>Trace why ↗</button></td></tr>)}</tbody></table>{!items.length && <div className="empty"><span>◈</span><h3>{txs.length ? 'No matching payments.' : 'Your financial firewall is ready.'}</h3><p>{txs.length ? 'Try a different search or decision filter.' : 'Run a scenario to follow the evidence before money moves.'}</p></div>}</div>; }
    function riskPanel(t: Transaction) { return <section className="panel"><div className="panel-heading"><h3>Risk assessment</h3><span className="muted">Rules v1.0</span></div><div className="risk-content">{[['Fraud risk', t.assessment.fraud], ['Intent risk', t.assessment.intent], ['Policy risk', t.assessment.policy]].map(([label, value]) => <div className="risk-line" key={label}><div><span>{label}</span><b>{value}<small> / 100</small></b></div><div className="risk-bar"><i style={{ width: `${value}%`, background: Number(value) >= 80 ? '#bf625c' : Number(value) >= 45 ? '#c39c54' : '#4b957b' }}/></div></div>)}<p className="fineprint">Explainable rule scores, not fraud probabilities.</p></div></section>; }
    function verification(t: Transaction) { return <section className="panel verify-panel"><div className="panel-heading"><h3>Trusted-channel verification</h3><span className="badge">SIMULATED CONTACT</span></div><div className="padded">{t.verification ? <><div className={`verification-label ${t.verification.confirmed ? 'green' : 'red'}`}>{t.verification.confirmed ? '✓ Bank change verified' : t.evidence.account !== t.evidence.trustedAccount ? '⊘ Destination change denied' : '✓ Evidence reviewed'}</div><blockquote>“{t.verification.reply}”</blockquote><p className="fineprint">Source: previously registered vendor contact. Fixture response; no external message was sent.</p></> : <><p>Verify payment instructions using the contact in the trusted vendor record—not the incoming email.</p><button disabled={!!busy} onClick={() => act('verify', { id: t.id })}>{busy === 'verify' ? 'Investigating…' : 'Investigate through trusted contact →'}</button></>}{t.status === 'review' && <div className="review-form"><label htmlFor="review-note">Decision note</label><textarea id="review-note" value={note} onChange={e => setNote(e.target.value)} maxLength={500} placeholder="Document why this payment should proceed or be rejected."/><div className="actions"><button disabled={!!busy || note.trim().length < 3} onClick={() => act('review', { id: t.id, allow: false, reason: note })}>Reject payment</button><button className="primary" disabled={!!busy || !t.verification?.confirmed || note.trim().length < 3} onClick={() => act('review', { id: t.id, allow: true, reason: note })}>Approve & simulate payment</button></div>{!t.verification?.confirmed && <small className="muted">Approval unlocks after trusted verification.</small>}</div>}</div></section>; }
    return <div className="shell"><aside><a className="brand" href="/">◈ <span>AgentVault</span></a><div className="workspace">A <span>Acme workspace<small>Sandbox environment</small></span></div><p className="eyebrow">CONTROL CENTER</p><nav>{nav.map(([icon, label]) => <button key={label} className={page === label ? 'active' : ''} onClick={() => { setPage(label); setNode(null); setNotice(''); }}>{icon} &nbsp; {label}{label === 'Approvals' && pending.length > 0 && <b className="nav-count">{pending.length}</b>}</button>)}</nav><div className="aside-foot"><i style={{ background: data?.policy.enabled === false ? '#c39c54' : undefined }}/>{data?.policy.enabled === false ? 'Agent spending paused' : 'Firewall active'}<small>Every payment. Every decision.</small><div className="version">AGENTVAULT <span>v0.1 / SANDBOX</span></div></div></aside><div className="body"><header><span>Workspace <b>/</b> {page}</span><div className="header-right"><span className="badge">● &nbsp; Simulation mode</span><span className="avatar">AV</span></div></header><main><div className="heading"><div><p className="eyebrow">THE FINANCIAL FIREWALL FOR AI AGENTS</p><h1>{page === 'Overview' ? 'Autonomy, with boundaries.' : page === 'MoneyTrace' ? 'Follow the money. Find the why.' : page === 'Approvals' ? 'Your judgment. At the right moment.' : page === 'Security evals' ? 'Trust, put to the test.' : page === 'Policies' ? 'Set the limits of autonomy.' : page === 'Integrations' ? 'Connect the execution layer.' : 'Every payment has a story.'}</h1><p>{page === 'Overview' ? 'Your agents move fast. Make sure your money moves safely.' : page === 'MoneyTrace' ? 'From human authority to payment intent. Every source, every decision.' : page === 'Approvals' ? 'Sensitive payments stay paused until you verify and decide.' : page === 'Security evals' ? 'Measured results from repeatable, synthetic security scenarios.' : page === 'Policies' ? 'Deterministic controls enforced before any simulated settlement.' : page === 'Integrations' ? 'A guarded MCP tool surface, ready for your TrueForge runtime.' : 'Inspect the evidence behind every authorized, reviewed, and blocked payment.'}</p></div><button className="primary" disabled={!!busy || !data} onClick={() => act('run', { scenario, runId: crypto.randomUUID() })}>{busy === 'run' ? 'Evaluating payments…' : '▶  Run agent demo'}</button></div>
 {error && <div className="alert error" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}{notice && <div className="alert success" role="status">{notice}</div>}{!data && !error && <div className="panel empty" role="status">Connecting to your sandbox…</div>}
 {page === 'Overview' && <><section className="hero"><div><span className="badge">AGENTVAULT / AP AGENT</span><h2>Trust the agent.<br /><em>Verify the intent.</em></h2><p>Follow an invoice from human authority to payment.<br />See exactly where trust breaks—and stop it there.</p><div className="hero-steps">INVESTIGATE <span>→</span> AUTHORIZE <span>→</span> PROTECT</div></div><div className="vault-orbit"><div className="orbit-label">PROTECTED BY AGENTVAULT</div><div className="vault">◈</div><span className="orbit-pill">✓ &nbsp; Policy enforced</span></div></section><div className="scenario-picker"><div><b>Choose a scenario</b><small>Synthetic evidence · no real money moves</small></div><select aria-label="Demo scenario" value={scenario} onChange={e => setScenario(e.target.value)}><option value="all">Full demo · allow → block → review</option>{data?.scenarios.map(s => <option key={s.id} value={s.id}>{s.name} · {money(s.amount)}</option>)}</select></div><div className="metrics">{[[money(protectedTotal), 'Simulated value blocked', 'Intercepted before settlement'], [money(paid), 'Authorized payments', 'Simulated payments settled'], [String(pending.length), 'Pending approvals', 'Human checkpoints'], [String(txs.length), 'Payments evaluated', 'Persisted in this sandbox']].map(([v, l, d]) => <article key={l}><p>{l}</p><strong>{v}</strong><small>{d}</small></article>)}</div><section className="panel"><div className="panel-heading"><h3>Payment activity <span className="count">{txs.length}</span></h3><button className="text-button" onClick={() => setPage('Transactions')}>View all transactions ↗</button></div>{table(txs.slice(0, 5))}</section>{tx && <div className="two-col"><section className="panel"><div className="panel-heading"><h3>Execution replay</h3><span className="badge">DETERMINISTIC DEMO</span></div><div className="trace-list">{tx.trace.slice(0, replay || undefined).map((event, i) => <button className={`trace-event ${event.state}`} key={event.id} onClick={() => { setPage('MoneyTrace'); setNode(event); }}><span className="trace-index">{String(i + 1).padStart(2, '0')}</span><span><b>{event.label}</b><code>{event.tool}()</code></span><span className="trace-mark">{event.state === 'ok' ? '✓' : event.state === 'blocked' ? '⊘' : '!'}</span></button>)}</div><div className="panel-foot"><button className="text-button" onClick={() => setReplay(1)}>↻ Replay trace</button><span className="muted">{tx.evidence.vendor} · {money(tx.amount / 100)}</span></div></section>{riskPanel(tx)}</div>}</>}
 {page === 'Transactions' && <section className="panel"><div className="panel-heading"><input className="search" aria-label="Search payments" placeholder="Search vendor or invoice…" value={search} onChange={e => setSearch(e.target.value)}/><select aria-label="Filter by decision" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All decisions</option>{Object.entries(names).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div>{table(visible)}</section>}
 {page === 'MoneyTrace' && (tx ? <><div className="transaction-strip"><div><span className={`status ${tx.status}`}>● {names[tx.status]}</span><b>{tx.evidence.vendor}</b><span className="muted">{tx.invoice}</span><strong>{money(tx.amount / 100)}</strong></div><div className="actions"><select aria-label="Select transaction" value={tx.id} onChange={e => { setSelected(e.target.value); setNode(null); }}>{txs.map(t => <option key={t.id} value={t.id}>{t.invoice} · {names[t.status]} · {t.id.slice(0, 6)}</option>)}</select><button onClick={exportTrace}>↓ Export evidence</button></div></div><div className="money-layout"><section className="panel graph-panel"><div className="panel-heading"><h3>MoneyTrace <span className="beta">PROVENANCE</span></h3><span className="muted">Select any step to inspect evidence</span></div><div className="graph">{tx.trace.map((e, i) => <div className="graph-step" key={e.id}>{i > 0 && <div className="connector">↓</div>}<button className={`graph-node ${e.state} ${node?.id === e.id ? 'chosen' : ''}`} onClick={() => setNode(e)}><span className="node-type">{e.source.toUpperCase()}</span><strong>{e.label}</strong><code>{e.tool}()</code><span className="node-arrow">↗</span></button></div>)}</div></section><div className="evidence-column"><section className="panel"><div className="panel-heading"><h3>{node?.label ?? 'Evidence inspector'}</h3></div><div className="padded">{node ? <><span className="badge">{node.source}</span><pre className="evidence-text">{node.detail}</pre><p className="fineprint">Recorded {new Date(node.at).toLocaleString()}<br />Source ID: {node.id}</p></> : <><p>Select a MoneyTrace node to see the source that contributed to the payment decision.</p><div className="conflict-comparison"><div><small>EMAIL DESTINATION</small><b>•••• {tx.evidence.account}</b><span>{tx.evidence.sender}</span></div><div><small>TRUSTED ERP RECORD</small><b>•••• {tx.evidence.trustedAccount}</b><span>{tx.evidence.domain}</span></div></div></>}</div></section>{riskPanel(tx)}<section className="panel"><div className="panel-heading"><h3>Decision factors</h3></div><div className="signals">{tx.assessment.signals.length ? tx.assessment.signals.map(s => <div key={s.code}><span className="signal-dot">!</span><div><b>{s.label}</b><p>{s.detail}</p></div></div>) : <p className="green">✓ Known vendor, approved invoice, matching amount and trusted destination.</p>}</div></section></div></div>{['blocked', 'review', 'rejected'].includes(tx.status) && verification(tx)}{tx.status === 'blocked' && tx.verification && !tx.verification.confirmed && tx.evidence.account !== tx.evidence.trustedAccount && <div className="loss-banner"><span>IMPERSONATION CONFIRMED IN SIMULATION</span><strong>{money(tx.amount / 100)} protected.</strong><p>The trusted vendor denied the bank change. The payment never settled.</p></div>}</> : <div className="panel empty"><h3>No money trail yet.</h3><p>Run the demo to build an evidence-backed payment trace.</p></div>)}
 {page === 'Approvals' && <>{pending.length ? <><section className="panel"><div className="panel-heading"><h3>Waiting for your decision</h3><span className="status review">{pending.length} paused</span></div>{table(pending)}</section><div className="approval-selector"><label htmlFor="approval">Review payment</label><select id="approval" value={pending.some(t => t.id === selected) ? selected : pending[0].id} onChange={e => { setSelected(e.target.value); setNote(''); }}>{pending.map(t => <option key={t.id} value={t.id}>{t.evidence.vendor} · {money(t.amount / 100)} · {t.id.slice(0, 6)}</option>)}</select></div>{verification(pending.find(t => t.id === selected) ?? pending[0])}</> : <div className="panel empty"><span>✓</span><h3>Nothing waiting on you.</h3><p>Payments that need judgment will appear here. Try the bank-change scenario.</p></div>}<p className="fineprint">Hard-blocked payments cannot be overridden from this queue. Each review is bound to one stored payment and its evidence.</p></>}
 {page === 'Security evals' && <><section className="eval-hero"><div><span className="eyebrow">REPEATABLE SECURITY CHECKS</span><h2>30 scenarios. No invented results.</h2><p>10 legitimate invoices · 5 bank changes · 5 impersonations · 5 injections · 5 policy violations</p></div><button className="primary" disabled={!!busy || !data} onClick={() => act('eval')}>{busy === 'eval' ? 'Running suite…' : 'Run evaluation suite →'}</button></section>{data?.evaluation ? <><div className="metrics">{[[`${data.evaluation.passed}/${data.evaluation.total}`, 'Scenarios passed'], [`${data.evaluation.attacksBlocked}/15`, 'Attacks & violations blocked'], [`${data.evaluation.legitimateAllowed}/10`, 'Legitimate invoices allowed'], [`${data.evaluation.medianMs.toFixed(3)} ms`, 'Median rule evaluation']].map(([v, l]) => <article key={l}><p>{l}</p><strong>{v}</strong><small>Measured {new Date(data.evaluation!.at).toLocaleTimeString()}</small></article>)}</div><div className="alert neutral">{data.evaluation.scope} No model calls or model cost are claimed.</div><section className="panel"><div className="panel-heading"><h3>Scenario results</h3><span className="muted">False positives: {data.evaluation.falsePositives} · Reviews: {data.evaluation.reviews}</span></div><div className="table-scroll"><table><thead><tr><th>SCENARIO</th><th>EXPECTED</th><th>ACTUAL</th><th>LATENCY</th><th>RESULT</th></tr></thead><tbody>{data.evaluation.rows.map(r => <tr key={r.id}><td>{r.name}</td><td>{r.expected}</td><td>{r.actual}</td><td>{r.ms.toFixed(3)} ms</td><td><span className={r.pass ? 'green' : 'red'}>{r.pass ? '✓ Pass' : '✕ Fail'}</span></td></tr>)}</tbody></table></div></section></> : <div className="panel empty"><span>⊞</span><h3>Measure before you trust.</h3><p>Run the suite to see actual results from the authorization engine.</p></div>}</>}
 {page === 'Policies' && <form className="panel policy-form" onSubmit={e => { e.preventDefault(); act('policy', { policy: draft }); }}><div className="panel-heading"><h3>AP agent spending policy</h3><span className="badge">USD ONLY</span></div><div className="padded"><div className="policy-toggle"><div><h3>Agent spending</h3><p>Pause new authorizations and settlements immediately.</p></div><label className="toggle"><input type="checkbox" checked={draft.enabled} onChange={e => setDraft({ ...draft, enabled: e.target.checked })}/><span>{draft.enabled ? 'Enabled' : 'Paused'}</span></label></div><div className="form-grid"><label>Maximum per payment ($)<input type="number" min="1" max="1000000" step="0.01" required value={draft.maxPayment} onChange={e => setDraft({ ...draft, maxPayment: Number(e.target.value) })}/><small>Hard block above this amount.</small></label><label>Daily budget ($)<input type="number" min={draft.maxPayment} max="10000000" step="0.01" required value={draft.dailyBudget} onChange={e => setDraft({ ...draft, dailyBudget: Number(e.target.value) })}/><small>UTC day; includes settled and reserved payments.</small></label><label>Human-review risk threshold<input type="number" min="10" max="79" required value={draft.reviewThreshold} onChange={e => setDraft({ ...draft, reviewThreshold: Number(e.target.value) })}/><small>Scores at or above 80 are always blocked.</small></label></div><div className="policy-fixed"><b>Always enforced</b><p>Approved invoice · exact amount match · USD currency · registered vendor · positive amount · prompt-injection block · trusted verification for bank changes</p></div><button className="primary" disabled={!!busy || !data} type="submit">{busy === 'policy' ? 'Saving…' : 'Save policy'}</button></div></form>}
 {page === 'Integrations' && <><div className="integration-grid">{[['TrueForge', 'External runtime', 'Not connected', 'Runs the agent investigation and streams tool calls. Configure your server and saved AP agent using the included integration guide.'], ['AgentVault MCP', 'Guarded tool endpoint', 'Token required', 'Email, ERP, authorization, verification, payment status, and simulated settlement tools. Agents cannot approve their own review requests.'], ['Payment rail', 'Simulated settlement', 'Sandbox only', 'Server-side authorization, budget reservation, and idempotent receipts. No bank or card credentials are used.']].map(([name, kind, status, desc]) => <section className="panel integration-card" key={name}><div className="integration-icon">{name === 'TrueForge' ? '⌘' : name === 'AgentVault MCP' ? '◈' : '⇄'}</div><span className="eyebrow">{kind}</span><h2>{name}</h2><p>{desc}</p><span className="badge">{status}</span></section>)}</div><section className="panel"><div className="panel-heading"><h3>Runtime boundary</h3></div><div className="padded"><div className="architecture">Human authority <span>→</span> TrueForge <span>→</span> AgentVault MCP <span>→</span> Policy gate <span>→</span> Mock payment</div><p>The dashboard demo uses a deterministic local workflow. It does not claim live TrueForge execution. The included runner connects a configured TrueForge agent to the same guarded payment tools.</p><p className="fineprint">Workspace identifier for your runtime configuration:</p><code className="workspace-code">{data?.workspace ?? 'Loading…'}</code><p><a className="text-link" href="https://trueforge.dev/api/quickstart" target="_blank" rel="noreferrer">TrueForge SDK documentation ↗</a></p></div></section></>}
 <footer><span>◈ AgentVault <span className="footer-dot">·</span> Evidence before execution.</span><span>Synthetic fixtures. Simulated payments. Real policy checks.</span></footer></main></div></div>;
}
